run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - unused
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: false
  staticcheck:
    checks:
      - "all"
